require 'massive_record/orm/relations/proxy'
require 'massive_record/orm/relations/proxy/references_one'
require 'massive_record/orm/relations/proxy/references_one_polymorphic'
require 'massive_record/orm/relations/proxy/references_many'
require 'massive_record/orm/relations/metadata'
require 'massive_record/orm/relations/interface'
